### ISSUE TITLE
DELETE /api/me (student) returns 500 internal server error

### ISSUE THREAD

**Issue by adriangoransson** [careerfairsystems/nexpo-backend#28]
Tested with student1 and student2. It works for companies though.

Terminal output for server below.

Updating the user (PUT endpoint) seems to work fine.

```
[debug] QUERY OK source="users_roles" db=0.9ms
DELETE FROM "users_roles" AS u0 WHERE (u0."user_id" = $1::bigint) [2]
2020-10-18 12:50:22.866 CEST [12118] ERROR:  update or delete on table "students" violates foreign key constraint "blips_student_id_fkey" on table "blips"
2020-10-18 12:50:22.866 CEST [12118] DETAIL:  Key (id)=(1) is still referenced from table "blips".
2020-10-18 12:50:22.866 CEST [12118] STATEMENT:  DELETE FROM "students" AS s0 WHERE (s0."user_id" = $1)
[debug] QUERY ERROR source="students" db=432.6ms
DELETE FROM "students" AS s0 WHERE (s0."user_id" = $1) [2]
[debug] QUERY OK db=1.1ms
rollback []
[info] Sent 500 in 925ms
[error] #PID<0.866.0> running Nexpo.Endpoint (cowboy_protocol) terminated
Server: localhost:4000 (http)
Request: DELETE /api/me
** (exit) an exception was raised:
    ** (Postgrex.Error) ERROR 23503 (foreign_key_violation): update or delete on table "students" violates foreign key constraint "blips_student_id_fkey" on table "blips"

    table: blips
    constraint: blips_student_id_fkey

Key (id)=(1) is still referenced from table "blips".
        (ecto 2.2.12) lib/ecto/adapters/sql.ex:440: Ecto.Adapters.SQL.execute_or_reset/7
        (ecto 2.2.12) lib/ecto/repo/schema.ex:719: anonymous fn/6 in Ecto.Repo.Schema.delete_assocs/5
        (elixir 1.10.4) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ecto 2.2.12) lib/ecto/repo/schema.ex:716: Ecto.Repo.Schema.delete_assocs/5
        (ecto 2.2.12) lib/ecto/repo/schema.ex:376: anonymous fn/9 in Ecto.Repo.Schema.do_delete/4
        (ecto 2.2.12) lib/ecto/repo/schema.ex:774: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
        (ecto 2.2.12) lib/ecto/adapters/sql.ex:576: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
        (db_connection 1.1.3) lib/db_connection.ex:1283: DBConnection.transaction_run/4
        (db_connection 1.1.3) lib/db_connection.ex:1207: DBConnection.run_begin/3
        (db_connection 1.1.3) lib/db_connection.ex:798: DBConnection.transaction/3
        (ecto 2.2.12) lib/ecto/repo/schema.ex:147: Ecto.Repo.Schema.delete!/4
        (nexpo 0.0.2) web/controllers/user_controller.ex:180: Nexpo.UserController.delete_me/4
        (nexpo 0.0.2) web/controllers/user_controller.ex:1: Nexpo.UserController.action/2
        (nexpo 0.0.2) web/controllers/user_controller.ex:1: Nexpo.UserController.phoenix_controller_pipeline/2
        (nexpo 0.0.2) lib/nexpo/endpoint.ex:1: Nexpo.Endpoint.instrument/4
        (phoenix 1.3.4) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
        (nexpo 0.0.2) lib/nexpo/endpoint.ex:1: Nexpo.Endpoint.plug_builder_call/2
        (nexpo 0.0.2) lib/plug/debugger.ex:132: Nexpo.Endpoint."call (overridable 3)"/2
        (nexpo 0.0.2) lib/nexpo/endpoint.ex:1: Nexpo.Endpoint.call/2
        (plug_cowboy 1.0.0) lib/plug/cowboy/handler.ex:18: Plug.Adapters.Cowboy.Handler.upgrade/4
```

**Comment by mu1664al-s** [comment]
The primary goal of this issue is solved. However, removing a student that have connections to companies is causing problems.
